### PR TITLE
fix: labeler.yml issue

### LINKED ISSUE #19: 🚀 [labeller] - automate issue labelling
### Is your feature request related to a problem ? Please describe. ✍️

I have added `labeler.yml`, but it does not seem to work properly
Update it if required and make one random issue named **labeler checker** I will remove it later, once I verify labeler.yaml is working

### Describe briefly how you would implement this enhancement.

```bash
Nan
```

### Additional context or screenshots

Nan

### Are you contributing for a program?

Other

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

### PR DESCRIPTION
**Pull request by DhruvChadha22**
Fixes #19 
Please add GSSOC and level labels to this PR as it is required to be counted in the leaderboards for me.

### CODE REVIEW

**Comment by Girishbari** [comment]
I have already added labels to issue itself, as per my knowledge that would do

**Comment by DhruvChadha22** [comment]
Yeah, I thought so too but they have updated us on discord that only PRs with labels will count and Issues with labels won't. You might even have to update the previously merged PRs for other contributors.

**Comment by Girishbari** [comment]
do me one thing share there discord server link

**Comment by DhruvChadha22** [comment]
@Girishbari sure, here is the Discord [Link](https://discord.com/invite/eMB9cpp9Y4)

This is what they shared with us:
image

**Pull request merged**
