### PR TITLE
Js to Ts conversion successful

### PR DESCRIPTION
**Pull request by prabh1234assla**
1. _**Js** to **ts**_ conversion for both server and client modules(in apps directory of **monorepo**) done.
2. **ts-node** is used as dev dependency for running **server.ts**.
3. **ts-config** is shared config between both server and client modules and thus in packages module.
4. Some functions were not declared like **_catchAsync_** and **_signToken_** and thus been declared also.
5. In nextjs or Client module, I have used **tsx**.

**Fix :** #22

### CODE REVIEW

**Comment by Girishbari** [comment]
@prabh1234assla mention issue number, in your comment like ***Fix #something ****

**Comment by prabh1234assla** [comment]
i have added issue number both in latest commit and the original merge request message

**Comment by Girishbari** [comment]
please resolve the conflict

**Comment by prabh1234assla** [comment]
I have resolved the conflicts.

**Pull request merged**
