### PR TITLE
📚 [Documentation] - Update README.md

### PR DESCRIPTION
**Pull request by iamkanhaiyakumar**
Update README.md
issue #38 slove

### CODE REVIEW

**Comment by iamkanhaiyakumar** [comment]
@Girishbari sir can you merged my PR

**Comment by Girishbari** [comment]
there are conflicts please resolve it

**Review by iamkanhaiyakumar — COMMENTED** [review]
Resolve it now cam you merged

**Comment by iamkanhaiyakumar** [comment]
@Girishbari Sir can you lebel  it. (Level 2)

**Pull request merged**
