### PR TITLE
Removed components to packages

### LINKED ISSUE #40: 🚀 [Refactor] - Move all the components from app/component to packages
### Is your feature request related to a problem ? Please describe. ✍️

there is a packages folder in Monorepo that can be utilized for all UI components, you will have to move the components and update all the respective import statements

### Describe briefly how you would implement this enhancement.

```bash
nan
```

### Additional context or screenshots

nan

### Are you contributing for a program?

GSSoC2024

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

### PR DESCRIPTION
**Pull request by Sujal7ss**
fixes #40

### CODE REVIEW

**Comment by Girishbari** [comment]
@sujal did you also updated all the import statements

**Comment by Sujal7ss** [comment]
Navbar with login and signup options is the only new file i found to update the import statements.
If there are any other files please let me know.
Also there is styling problems in the updated navbar. PTAL

**Comment by Girishbari** [comment]
okay, have ran the frontend, could you send me screenshot

**Comment by Sujal7ss** [comment]
image
image

**Pull request merged**
