### PR TITLE
Repo to Monorepo conversion

### PR DESCRIPTION
**Pull request by prabh1234assla**
Converted the project into a monorepo using TURBOREPO as a dependency.

**Fix:** #14

### CODE REVIEW

**Comment by Girishbari** [comment]
hey @prabh1234assla, there are some conflicts which you will need to resolve in  your end, I also need to ask you, did you run the project using turbo dev then did the project ran..?

**Comment by prabh1234assla** [comment]
Screenshot from 2024-05-20 22-19-42
Projects ran successfully. `turbo dev` command runs both the client and server codes without any errors.

**Comment by prabh1234assla** [comment]
Sir I have finally resolved the conflicts.

**Comment by Girishbari** [comment]
@prabh1234assla  mention issue number, in your comment like ***Fix #something ****

**Comment by prabh1234assla** [comment]
added issue number both in latest commit and the original merge request message

**Pull request merged**
